from django.contrib import admin
from . models import *
# Register your models here.
admin.site.register(employee)
admin.site.register(stud_details)
admin.site.register(subjects)
admin.site.register(faculty)
admin.site.register(Department)
admin.site.register(TempLectures)
admin.site.register(attendance)
admin.site.register(lectureEnrollment)
admin.site.register(school)
admin.site.register(program)
admin.site.register(lectureRecord)
admin.site.register(quizInfo)
admin.site.register(quizQuestions)
admin.site.register(quizGrades)
admin.site.register(assignment)
admin.site.register(assignmentSubmission)
admin.site.register(modes)
admin.site.register(weightage)