# Generated by Django 3.0.5 on 2021-05-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentID', models.CharField(max_length=10)),
                ('DepartmentName', models.CharField(max_length=100)),
                ('HeadOfDepartment', models.EmailField(max_length=254)),
                ('SpecializedCourse', models.BooleanField()),
                ('StartDate', models.DateField()),
                ('School', models.CharField(max_length=15)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.EmailField(max_length=254)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('Doj', models.DateField()),
                ('Etype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyID', models.EmailField(max_length=254)),
                ('FacultyName', models.CharField(max_length=50)),
                ('Ftype', models.CharField(max_length=30)),
                ('FieldOfExpertise', models.CharField(max_length=50)),
                ('FieldOfInterest1', models.CharField(max_length=35)),
                ('FieldOfInterest2', models.CharField(max_length=35)),
                ('FieldOfInterese3', models.CharField(max_length=35)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
            ],
        ),
        migrations.CreateModel(
            name='TempLectures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TempLectureID', models.CharField(max_length=15)),
                ('LectureTitle', models.CharField(max_length=500)),
                ('Semester', models.IntegerField()),
                ('Credit', models.CharField(max_length=10)),
                ('TempLessonPlan', models.FileField(upload_to='media')),
                ('CreatedBy', models.EmailField(max_length=254)),
                ('LectureStatus', models.CharField(max_length=15)),
                ('Changes', models.FileField(upload_to='media')),
                ('LastChangesMadeBy', models.CharField(max_length=30)),
                ('LastApprovedBy', models.CharField(max_length=30)),
                ('NextSendTo', models.CharField(max_length=15)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
            ],
        ),
        migrations.CreateModel(
            name='stud_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('EnrollmentNumber', models.CharField(max_length=10)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(max_length=35)),
                ('Specialization', models.CharField(blank=True, max_length=35)),
                ('BatchYear', models.CharField(max_length=10)),
                ('CurrSem', models.IntegerField()),
                ('Residential', models.BooleanField()),
                ('AccomodationID', models.BigIntegerField()),
                ('UniversityEmailID', models.CharField(max_length=100)),
                ('PersonalEmailID', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('StreetAddress', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=20)),
                ('PinCode', models.IntegerField()),
                ('ProtectedClass', models.CharField(blank=True, max_length=3)),
                ('LastQualification', models.CharField(max_length=5)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
            ],
        ),
        migrations.CreateModel(
            name='lectures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LectureID', models.CharField(max_length=10)),
                ('LectureName', models.CharField(max_length=50)),
                ('LessonPlan', models.FileField(upload_to='media')),
                ('Semester', models.IntegerField()),
                ('Credit', models.CharField(max_length=10)),
                ('LastTaughtBy', models.EmailField(max_length=254)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department')),
                ('TaughtBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='lectureRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goals', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('notes', models.FileField(upload_to='')),
                ('facultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
            ],
        ),
        migrations.CreateModel(
            name='lectureEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details')),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LastUpdatedOn', models.DateField()),
                ('attendanceFile', models.FileField(upload_to='attendance')),
                ('FacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
                ('LectureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
            ],
        ),
    ]
