# Generated by Django 3.0.5 on 2021-05-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20210504_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.employee')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.school')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.school'),
        ),
    ]
