# Generated by Django 3.0.5 on 2021-05-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20210504_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HeadOfDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.employee'),
        ),
    ]
