# Generated by Django 3.0.5 on 2021-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20210504_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='FacultyName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FieldOfExpertise',
        ),
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='FacultyID',
            field=models.CharField(max_length=10),
        ),
    ]
