# Generated by Django 3.0.5 on 2021-05-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20210504_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
