# Generated by Django 3.0.5 on 2021-05-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_auto_20210504_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_details',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program'),
        ),
    ]
