# Generated by Django 3.0.5 on 2021-05-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_lectures_lasttaughtby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureenrollment',
            old_name='lectureId',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='lectureenrollment',
            old_name='studentID',
            new_name='student',
        ),
    ]
