# Generated by Django 3.2 on 2021-05-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_lectures_taughtby'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('assignmentFile', models.FileField(upload_to='')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='assignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submissionFile', models.FileField(upload_to='')),
                ('submitedOn', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.assignment')),
                ('submitedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('takenOn', models.DateTimeField(auto_now_add=True)),
                ('attendies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details')),
            ],
        ),
        migrations.CreateModel(
            name='modes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='quizGrades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='quizInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('quizDate', models.DateField()),
                ('quizStartTime', models.TimeField()),
                ('quizEndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='quizQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('correctOption', models.CharField(max_length=1000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.quizinfo')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subjectCode', models.CharField(max_length=10)),
                ('subjectName', models.CharField(max_length=50)),
                ('LessonPlan', models.FileField(upload_to='media')),
                ('Semester', models.IntegerField()),
                ('Credit', models.CharField(max_length=10)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='weightage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.CharField(max_length=5)),
                ('validTill', models.DateField()),
                ('assignedOn', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='TaughtBy',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeID',
            new_name='employeeID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='personalEmail',
        ),
        migrations.RenameField(
            model_name='lecturerecord',
            old_name='facultyId',
            new_name='faculty',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Etype',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FieldOfInterese3',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FieldOfInterest1',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='FieldOfInterest2',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Ftype',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='lecturerecord',
            name='lectureId',
        ),
        migrations.AddField(
            model_name='employee',
            name='universityEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='FacultyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.employee'),
        ),
        migrations.DeleteModel(
            name='attendence',
        ),
        migrations.AddField(
            model_name='weightage',
            name='assignedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='weightage',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.modes'),
        ),
        migrations.AddField(
            model_name='weightage',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='TaughtBy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='quizinfo',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
        ),
        migrations.AddField(
            model_name='quizgrades',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.quizinfo'),
        ),
        migrations.AddField(
            model_name='quizgrades',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
        ),
        migrations.AddField(
            model_name='lecturerecord',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lectureenrollment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subjects'),
        ),
        migrations.DeleteModel(
            name='lectures',
        ),
    ]
