# Generated by Django 3.2 on 2021-05-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20210526_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_details',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='AccomodationID',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='CurrSem',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='MiddleName',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='ProtectedClass',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='Residential',
        ),
        migrations.RemoveField(
            model_name='stud_details',
            name='Specialization',
        ),
        migrations.AlterField(
            model_name='stud_details',
            name='LastQualification',
            field=models.CharField(max_length=100),
        ),
    ]
