# Generated by Django 3.2 on 2021-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_auto_20210527_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stud_details',
            name='currentSemester',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
