# Generated by Django 3.2 on 2021-05-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_auto_20210527_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='duration',
            new_name='totalSemester',
        ),
    ]
