# Generated by Django 3.2 on 2021-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_rename_duration_program_totalsemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='questionType',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
