# Generated by Django 3.2 on 2021-05-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_quizquestions_questiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizinfo',
            old_name='lecture',
            new_name='subject',
        ),
    ]
