# Generated by Django 3.2 on 2021-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_rename_lecture_quizinfo_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
