# Generated by Django 3.2 on 2021-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_assignment_startingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinfo',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
