# Generated by Django 3.2 on 2021-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_quizinfo_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
