# Generated by Django 3.2 on 2021-06-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_auto_20210616_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgrades',
            name='submitedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizgrades',
            name='timeTaken',
            field=models.DurationField(null=True),
        ),
    ]
