# Generated by Django 3.2 on 2021-06-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_auto_20210616_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightage',
            name='validTill',
        ),
        migrations.AlterField(
            model_name='weightage',
            name='assignedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.employee'),
        ),
    ]
