# Generated by Django 3.2 on 2021-06-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_rename_subjects_weightage_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightage',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AddField(
            model_name='weightage',
            name='validTill',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightage',
            name='assignedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
    ]
