# Generated by Django 3.2 on 2021-06-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_auto_20210622_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentType',
            field=models.CharField(choices=[('CA', 'Class'), ('HA', 'Home')], max_length=2, null=True),
        ),
    ]
