# Generated by Django 3.2 on 2021-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_assignment_assignmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgrades',
            name='timeTaken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
